// Code generated by scripts/generate.sh. DO NOT EDIT.

package oxinsider

// Which OpenAPI document this release was generated from. OpenAPISHA256 is
// the SHA-256 of the document bytes as fetched; AppCommit is the
// 0xinsider/0xinsider commit that last changed web/public/api/v1/openapi.json
// when it could be resolved, else "". Compare OpenAPISHA256 with the live
// document to see whether a release is behind the API.
const (
	OpenAPISource  = "0xinsider/0xinsider:web/public/api/v1/openapi.json"
	OpenAPISHA256  = "8d648c728b525eea69814f0bb0056aa05b447525a32ec868fef7711f903aa4b5"
	OpenAPIVersion = "1.0.0"
	OperationCount = 64
	AppRepository  = "0xinsider/0xinsider"
	AppSpecPath    = "web/public/api/v1/openapi.json"
	AppCommit      = "a138487e97eb1681d38a624d2bc4f12175584673"
)
