// Code generated by scripts/generate.sh. DO NOT EDIT.

package oxinsider

// Which OpenAPI document this release was generated from. OpenAPISHA256 is
// the SHA-256 of the document bytes as fetched; AppCommit is the
// 0xinsider/0xinsider commit that last changed web/public/api/v1/openapi.json
// when it could be resolved, else "". Compare OpenAPISHA256 with the live
// document to see whether a release is behind the API.
const (
	OpenAPISource  = "0xinsider/0xinsider:web/public/api/v1/openapi.json"
	OpenAPISHA256  = "82b5d87547bbe138d58407bb697e991c9f3751a7a49e8e042771729dd4d9ac9f"
	OpenAPIVersion = "1.0.0"
	OperationCount = 88
	AppRepository  = "0xinsider/0xinsider"
	AppSpecPath    = "web/public/api/v1/openapi.json"
	AppCommit      = "c083740715c4f031806ad0f8a24769be4f3db99c"
)
