// Code generated by scripts/generate.sh. DO NOT EDIT.

package oxinsider

// Which OpenAPI document this release was generated from. OpenAPISHA256 is
// the SHA-256 of the document bytes as fetched; AppCommit is the
// 0xinsider/0xinsider commit that last changed web/public/api/v1/openapi.json
// when it could be resolved, else "". Compare OpenAPISHA256 with the live
// document to see whether a release is behind the API.
const (
	OpenAPISource  = "https://0xinsider.com/api/v1/openapi.json"
	OpenAPISHA256  = "c18d77811bc19e97dc1e65c8558d62ca2858b2144c7e2f295da950a53f0341de"
	OpenAPIVersion = "1.0.0"
	OperationCount = 83
	AppRepository  = "0xinsider/0xinsider"
	AppSpecPath    = "web/public/api/v1/openapi.json"
	AppCommit      = ""
)
