#!/usr/bin/env bash
# Regenerate the typed client from the published OpenAPI document, and record
# which document it came from in provenance.go.
#
#   ./scripts/generate.sh              # fetch https://0xinsider.com/api/v1/openapi.json
#   SPEC=path/to/openapi.json ./scripts/generate.sh
#   APP_COMMIT=<sha> ./scripts/generate.sh   # the 0xinsider/0xinsider commit the document belongs to
#
# The bracketed query aliases (`expand[]`) are backward-compatible spellings of
# `expand`; they collide with the canonical parameter in Go names, so they are
# dropped before generation. Requests from this SDK always use `expand`.
#
# provenance.go records the SHA-256 of the document bytes as fetched (before
# the alias filter), its info.version, the operation count, and the app commit
# that last changed web/public/api/v1/openapi.json in 0xinsider/0xinsider:
# APP_COMMIT when set, else a lookup of the GitHub commits API (GH_TOKEN is
# used when set). An app commit that cannot be resolved is recorded as ""
# and reported on stderr, never guessed.
set -euo pipefail
cd "$(dirname "$0")/.."
OAPI_CODEGEN_VERSION="v2.8.0"
APP_REPOSITORY="0xinsider/0xinsider"
APP_SPEC_PATH="web/public/api/v1/openapi.json"
DEFAULT_SOURCE="https://0xinsider.com/api/v1/openapi.json"
spec="${SPEC:-}"
source_label="$DEFAULT_SOURCE"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
if [ -z "$spec" ]; then
  curl -fsSL -A "0xinsider-go-generator" "$DEFAULT_SOURCE" -o "$tmp/openapi.json"
  spec="$tmp/openapi.json"
else
  source_label="${APP_REPOSITORY}:${APP_SPEC_PATH}"
fi
sha256="$(shasum -a 256 "$spec" | cut -d' ' -f1)"
version="$(jq -r '.info.version // "unknown"' "$spec")"
operation_count="$(jq '[.paths[] | to_entries[] | select(.key | IN("get","post","put","patch","delete")) | .value.operationId] | length' "$spec")"
app_commit="${APP_COMMIT:-}"
if [ -z "$app_commit" ]; then
  auth=()
  if [ -n "${GH_TOKEN:-${GITHUB_TOKEN:-}}" ]; then
    auth=(-H "Authorization: Bearer ${GH_TOKEN:-${GITHUB_TOKEN:-}}")
  fi
  app_commit="$(curl -fsSL -A "0xinsider-go-generator" -H "Accept: application/vnd.github+json" "${auth[@]}" \
    "https://api.github.com/repos/${APP_REPOSITORY}/commits?path=${APP_SPEC_PATH}&per_page=1" | jq -r '.[0].sha // empty' || true)"
  if [ -z "$app_commit" ]; then
    echo "warning: app commit not resolved from the GitHub API; recording \"\"" >&2
  fi
fi
# Filter through a temporary file: SPEC=openapi.sdk.json is a reasonable thing
# to type, and a redirect straight onto the destination would truncate the
# input before jq read it.
jq '(.paths[][] | objects | select(has("parameters")) | .parameters) |= map(select((.name // "") | endswith("[]") | not))' \
  "$spec" > "$tmp/openapi.sdk.json"
mv "$tmp/openapi.sdk.json" openapi.sdk.json
go run "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@${OAPI_CODEGEN_VERSION}" \
  -config scripts/oapi-codegen.yaml openapi.sdk.json
cat > provenance.go <<PROVENANCE
// Code generated by scripts/generate.sh. DO NOT EDIT.

package oxinsider

// Which OpenAPI document this release was generated from. OpenAPISHA256 is
// the SHA-256 of the document bytes as fetched; AppCommit is the
// 0xinsider/0xinsider commit that last changed web/public/api/v1/openapi.json
// when it could be resolved, else "". Compare OpenAPISHA256 with the live
// document to see whether a release is behind the API.
const (
	OpenAPISource  = "${source_label}"
	OpenAPISHA256  = "${sha256}"
	OpenAPIVersion = "${version}"
	OperationCount = ${operation_count}
	AppRepository  = "${APP_REPOSITORY}"
	AppSpecPath    = "${APP_SPEC_PATH}"
	AppCommit      = "${app_commit}"
)
PROVENANCE
gofmt -w provenance.go
gofmt -l . | (! grep .)
go vet ./...
go build ./...

# The hand-maintained transport policy lives outside the generated file, and
# only New installs it: the credential destination guard, the stream guard, and
# the request deadlines. A regeneration that rewrites the constructor or drops
# one of these files would leave requests unbounded or credentials unchecked,
# silently, so fail here instead.
policy_ok=1
require_policy() {
  if ! grep -qF "$2" "$1"; then
    echo "error: $1 no longer carries $3" >&2
    policy_ok=0
  fi
}
require_policy client.go 'newDefaultHTTPClient()' "the bounded default HTTP client (timeout.go)"
require_policy client.go 'deadlineDoer{' "the per-request deadline (timeout.go)"
require_policy client.go 'policyDoer{' "the credential and stream guard (policy.go)"
require_policy client.go 'withRedirectPolicy(' "the redirect downgrade guard (policy.go)"
require_policy timeout.go 'func (d deadlineDoer) Do(' "the doer that bounds an ordinary request"
require_policy timeout.go 'ResponseHeaderTimeout: DefaultResponseHeaderTimeout' "the transport's response-header bound"
require_policy stream.go 'func isStreamRequest(' "the predicate that keeps the event stream off the request deadline"
require_policy stream.go 'func newIdleGuard(' "the stream idle bound"
if [ "$policy_ok" -ne 1 ]; then
  echo "error: regeneration must not drop the hand-maintained transport policy; see AGENTS.md" >&2
  exit 1
fi

echo "generated ${operation_count} operations from ${source_label} (sha256 ${sha256}, app commit ${app_commit:-unknown})"
